### ISSUE TITLE
How can I make side panels work?

### ISSUE THREAD

**Issue by ztl8702** [ashvin777/framework7.angular#1]
Using `openPanel(position)` and `closePanel(position)` provided by Framework7. consider a ng-click event to trigger these?

**Comment by ronaldamadeu** [comment]
Same problem, any advice is welcome!

**Comment by ashvin777** [comment]
As of now you can put side panel html in index file itself. and you can out its logic in root controller. I am on the way to findout some solution about thus issue

**Comment by ashvin777** [comment]
Hi @ronaldamadeu and @ztl8702 

The new architectural changes in the plugin has removed all the limitations. Now you can enjoy all the components from Framework7 along with AngularJS.

So side panels will also work as it was working in Framework7 app.
Have a look at below demo url http://ashvin777.github.io/framework7.angular/kitchen-sink-material/#!/home.html

You can get the detailed explanation in the README.md doc.

Regards,
Ashvin
