### ISSUE TITLE
Can not read property get

### ISSUE THREAD

**Issue by phanivaranasi** [ashvin777/framework7.angular#11]
Hi,
I'm trying to integrate your angular plugin in my application...
Below is my case
I'm building Android app, with 
(AngularJS + RequireJS)
All went well, then I dump pages in index.html page, but when I separate code, in different pages
controllers which are loaded previous are not working.
So, I came across your plugin, after defining same as your kitchen application, I'm facing error 
![image](https://cloud.githubusercontent.com/assets/6230353/22922535/2e9e67c2-f2c4-11e6-8eac-c89c6f9fad6f.png)
--
In the below code I'm getting injector undefined
![image](https://cloud.githubusercontent.com/assets/6230353/22922568/58c462e0-f2c4-11e6-979c-f5a9ac63881f.png)

Could you let me know to fix it.

Thanks
Krishna

**Comment by ashvin777** [comment]
Hi, Sorry for being so late. Today only I came back from holidays.

I think the reason of this error could be that you missed to add ng-app in HTML tag like `<html ng-app>`. Try adding this and run it will start working.

:-)

**Comment by phanivaranasi** [comment]
Hey, Thanks for the repy.
after debugging I found that  $scope.$$childHead is null so I'm facing the issue.

**Comment by ashvin777** [comment]
OK. So is it resolved by applying the ng-app ?

**Comment by phanivaranasi** [comment]
Yes! I managed to fix the code. its running well. But I found $rootScope is not persisting when we navigate from one page to another.

**Comment by ashvin777** [comment]
Hi @phanivaranasi ,

I have released a fix in my current release. This was happening for the cases of manual bootstrap.

I have added the fix in the code.

Regards,
Ashvin
