### ISSUE TITLE
multilang

### ISSUE THREAD

**Issue by mohamedsalehamin** [ashvin777/framework7.angular#12]
can you add an exapmle to use mutli language

**Comment by ashvin777** [comment]
Sorry for the late reply. Just came back from vacation 😃 

I will add this into my todo item and will soon provide you an example.

**Comment by ashvin777** [comment]
Hi @7aduta ,

The multilang feature should be part of Framework7 library. This is just a plugin to add angularjs support in F7 app.

Closing as it is not relevant.

Regards,
Ashvin
