### ISSUE TITLE
ng rotue

### ISSUE THREAD

**Issue by mohamedsalehamin** [ashvin777/framework7.angular#13]
i have tried to use ng route with main branch and didn't get it write 
could you provide me with example to how to do so

**Comment by ashvin777** [comment]
What exact problem you are facing when you are trying to use ng-route ?

Is it that the page navigation not working or template not rendering properly ?

**Comment by ashvin777** [comment]
Hi @7aduta ,

This plugin doesn't support the ng-route. You have to use F7 router - framework7.io/docs/router-api.html.

Regards,
Ashvin
