### ISSUE TITLE
iOS swipe back

### ISSUE THREAD

**Issue by karaja** [ashvin777/framework7.angular#14]
Hi, i want use iOS swipe back features. 

My code is : 
animateNavBackIcon:false,
swipeBackPage: true,
pushState: true,
angular: true,
router: true

But swipe back doesn't work. 

Can you help me ?

Thanks.

**Comment by ashvin777** [comment]
can you share any demo example for this issue ? I will check this into that.

**Comment by ashvin777** [comment]
Sorry the iOS swipe back is not supported by this plugin.
