### ISSUE TITLE
Support for Latest Framework7

### ISSUE THREAD

**Issue by acedigibits** [ashvin777/framework7.angular#18]
This wrapper of angularjs is great. However, i found many of the latest functionality and elements missing as the framework7 version used by your library is 1.4.2 which is very old. Request you to upgrade wrapper for latest version. 

Also wanted to know how to trigger routing via js. I know of direct href but js one i used was window.location.hash ...dont know if that one is correct to use.

**Comment by ashvin777** [comment]
Hi @acedigibits ,

Thanks for pointing this out. I will upgrade the F7 library.

Regards the routing, as I have mentioned in the README.md use the default router of framework7 - http://framework7.io/docs/router-api.html

Regards,
Ashvin

**Comment by ashvin777** [comment]
Issue resolved. Closed #18.

**Comment by acedigibits** [comment]
when i do mainView.router.back(), my ng bindings do not work (ng-click, ng-show,etc.)

**Comment by acedigibits** [comment]
can u update to latest framework7 version? it has some new components.

**Comment by ashvin777** [comment]
Hi @acedigibits , you should be able to use this plugin along with latest framework7 versions. Try updating the framework7 library in your project which will work as expected. Let me know if you see any issue during that.
