### ISSUE TITLE
error in local launch

### ISSUE THREAD

**Issue by fcamisa** [ashvin777/framework7.angular#2]
I have downloaded the zip and I have installed on easyphp dev server.

I have this error:

Errore: Error: [$injector:unpr] http://errors.angularjs.org/1.4.7/$injector/unpr?p0=framework7Provider%20%3C-%20framework7
File sorgente: http://localhost/projects/framework7_angular/bower_components/angular/angular.min.js
Riga: 6

**Comment by fcamisa** [comment]
All OK in branch 'gh-pages'

**Comment by ashvin777** [comment]
Try gh-pages branch as of now.. Take the checkout from that branch.

**Comment by ashvin777** [comment]
Hi @fcamisa,

You can take the checkout now from the master branch. There are major changes done in the application architecture. Please have a look in the README.msd docs and let me know you valuable feedback and comments.

The new architectural changes in the plugin has removed all the limitations. Now you can enjoy all the components from Framework7 along with AngularJS.

Have a look at below demo url http://ashvin777.github.io/framework7.angular/kitchen-sink-material/#!/home.html

You can get the detailed explanation in the README.md doc.

Regards,
Ashvin
