### ISSUE TITLE
Integration with Angular 2

### ISSUE THREAD

**Issue by NBAMj** [ashvin777/framework7.angular#5]
Is it possible to integrate framework 7 with Angular2 ?

**Comment by ashvin777** [comment]
Hi NBAMj,

I haven't started much on Angular2. However I believe that there won't be any limitation for makeing it compatible with Angular2. 

I just need to figure out how to do that. Will update you on my investigations.

Regards,
Ashvin

**Comment by ashvin777** [comment]
Hi NBAMj,

Just fyi,
I have started working on Angular 2 integration with Framework7. Currently the repo is under development phase. Hoping to complete this soon
https://github.com/ashvin777/framework7.angular2

Will keep you posted :)

Regards,
Ashvin

**Comment by ashvin777** [comment]
Hi NBAMj,

I thought to share this with you. Just had couple of start screens working - checkout the demo app
https://ashvin777.github.io/framework7.angular2/www/#/home

Regards,
Ashvin
