### ISSUE TITLE
Links Issue with iOS styles

### ISSUE THREAD

**Issue by applecat** [ashvin777/framework7.angular#6]
If in example I change styles from Material:

```
<link rel="stylesheet" href="../build/css/framework7.material.css">
<link rel="stylesheet" href="../build/css/framework7.material.colors.css">
```

to iOS:

```
<link rel="stylesheet" href="../build/css/framework7.ios.css">
<link rel="stylesheet" href="../build/css/framework7.ios.colors.css">
```

then links in top tabs bars stop working on click in Safari and Firefox (they works in Chrome, but tab text disappeared while tab switch animation runs).

Why this is happens? (with Material styles everything works great). Is there is a possibility to fix this?

P.S. And there are some duplicate tabs in the bottom of the page:
![Image of Yaktocat](http://apple-cat.ru/github/f7-angular.png)

**Comment by ashvin777** [comment]
Thabks for raising this. I will get back to you soon on this.

**Comment by ashvin777** [comment]
So I checked today in my chrome browser. The links in the top and bottom both are working fine for both the themes. If it doesn't work at your side then try to call "window.application.init()" this inside home controller.

The link in the bottom and top is related to Framework7 structure. For iOS specific we may to hide the toolbar links but for Android we need that.
