### ISSUE TITLE
Ng Cloak

### ISSUE THREAD

**Issue by iMestav** [ashvin777/framework7.angular#7]
Hi, ng-cloak doesn't work. How i fix this problem ? Thanks

**Comment by ashvin777** [comment]
On which element you have added the ng-cloak ? Can you try adding the ng-cloak to each controller binding and try again.

**Comment by iMestav** [comment]
Thanks ashvin. It's work perfect. 
I have a problem too. 

I want use ng-route or ui-router. But i guess this codes doesn't support to ng-route or ui-router.
What can i do to use it ? 

Thanks again.

**Comment by ashvin777** [comment]
Actually you can directly use ng-route or ui-router in your app. FYI, I have implemented this integration first using ng-router and ui-router only :smiley:  . Checkout the link below for the source -

https://github.com/ashvin777/framework7.angular/tree/855668145685f97f421cef2833d71106cc5d11ae

**Comment by ashvin777** [comment]
Created a proper branch for it : https://github.com/ashvin777/framework7.angular/tree/v1.0(ui-router)

**Comment by iMestav** [comment]
Thanks again.
