### ISSUE TITLE
deviceready event not firing

### ISSUE THREAD

**Issue by ashokkumar88** [ashvin777/framework7.angular#8]
hi,

I am calling the deviceready event from separate file. but it is not firing. what is the correct place to call deviceready event.

**Comment by ashvin777** [comment]
It should work as it is jquery. Have you included the js file in your main index.html ? Can you post some code to check

**Comment by ashokkumar88** [comment]
Hi, 
Thanks for the reply.
It is working. actually i forgot to add cordova.js in index.html.

**Comment by ashvin777** [comment]
:+1:
